site_name: Entornos de desarrollo

theme:
  name: material
  language: es
  custom_dir: overrides
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Modo Claro
  features:
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - content.code.copy
    - content.code.select

nav:
  - Inicio: index.md
  - Tema 1:
      - Tema 1 - Introducción: tema1/index.md
      - Concepto de programa informático: tema1/concepto.md
      - Actividad 1.1: tema1/actividad_1_1.md
      - Código fuente, objeto y ejecutable: tema1/codigo.md
      - Actividad 1.2: tema1/actividad_1_2.md
      - Lenguajes: tema1/lenguajes.md
      - Actividad 1.3: tema1/actividad_1_3.md
      - Fases del desarrollo: tema1/fases.md
      - Actividad 1.4: tema1/actividad_1_4.md
      - Herramientas: tema1/herramientas.md
      - Actividad 1.5: tema1/actividad_1_5.md
      - Metodologías: tema1/metodologias.md
      - Uso de Jira: tema1/uso-jira.md
      - Actividad 1.6: tema1/actividad_1_6.md
  - Tema 2:
      - Tema 2 - Introducción: tema2/index.md
      - Entornos de desarrollo: tema2/entornos-de-desarrollo.md
      - Actividad 2.1: tema2/actividad_2_1.md
      - Actividad 2.2: tema2/actividad_2_2.md
      - Actividad 2.3: tema2/actividad_2_3.md
      - Actividad 2.4: tema2/actividad_2_4.md
      - Actividad 2.5: tema2/actividad_2_5.md
  - Tema 3:
      - Tema 3 - Introducción: tema3/index.md
      - Depuración: tema3/depuracion.md
      - Actividad 3.1: tema3/actividad_3_1.md
      - Pruebas de software: tema3/pruebas.md
      - Técnicas de casos de prueba: tema3/casos.md
      - Actividad 3.2: tema3/actividad_3_2.md
      - Actividad 3.3: tema3/actividad_3_3.md
      - Actividad 3.4: tema3/actividad_3_4.md
      - Pruebas unitarias: tema3/unitarias.md
      - Actividad 3.5: tema3/actividad_3_5.md
      - Actividad 3.6: tema3/actividad_3_6.md
  - Tema 4:
      - Tema 4 - Introducción: tema4/index.md
      - Optimización y tipos: tema4/optimizacion_y_tipos.md
      - Actividad 4.1: tema4/actividad_4_1.md
      - Refactorización: tema4/refactorizacion.md
      - Actividad 4.2: tema4/actividad_4_2.md
      - Analizadores de código: tema4/analizadores.md
      - Documentación del código: tema4/documentacion.md
      - Actividad 4.3: tema4/actividad_4_3.md
      - Introducción a Git: tema4/introduccion-git.md
      - Actividad 4.4: tema4/actividad_4_4.md







markdown_extensions:
  - md_in_html
  - attr_list
  - admonition             # (solo una vez)
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:    # usa este, NO 'codehilite'
      anchor_linenums: true
      linenums: true
      auto_title: true
      pygments_lang_class: true
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:  # habilita Mermaid como fence
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/extra.css
  
plugins:
  - search
  - mkdocs-pdf